[target.wasm32-unknown-unknown]
rustflags = [
  "-C", "link-arg=-z",
  "-C", "link-arg=stack-size=1048576",
  "-C", "link-arg=--initial-memory=16777216",
  "-C", "link-arg=--max-memory=16777216",
  "-C", "target-feature=-reference-types",
]
